language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI server HOME
before_install:
  - chmod +x gradlew
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# s3 setting and zip file save
before_deploy:
  - zip -r spring-book *
  - mkdir -p deploy
  - mv spring-book.zip deploy/spring-book.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-book-sh-travis-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true


#CI perform end >> email alert
notifications:
  email:
    recipients:
      - dusghk1717@gmail.com
