language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI server HOME
before_install:
  - chmod +x gradlew
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# s3 setting and zip file save
before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/spring-book.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: spring-book-sh-travis-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-book-sh-travis-build
    key: spring-book.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: spring-book-deploy # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: spring-book-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true


#CI perform end >> email alert
notifications:
  email:
    recipients:
      - dusghk1717@gmail.com